[project]
name = "cursadas"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "lxml>=6.0.2",
    "pandas>=3.0.1",
    "polars>=1.38.1",
    "prettytable>=3.17.0",
    "requests>=2.32.3",
    "tabulate>=0.9.0",
]
